### ISSUE TITLE
Sound response not working?

### ISSUE THREAD

**Issue by Caaz** [Zombiefied7/ZombiefiedZombieApocalpyse#4]
Got a colonist firing on a few zombies on the map, I'd think they'd respond to the gunfire but it really doesn't seem like they are.

How do zombies react to sound in code? How are they supposed to in game?

**Comment by Zombiefied7** [comment]
All the zombies should move to the last shooting location. Last I checked before uploading to steam it did work

**Comment by Zombiefied7** [comment]
Yep I just checked again and its still working for me. Can you give more info about your situation? Might be a situational bug problem

**Comment by Caaz** [comment]
Absolutely right, it's a situational thing. When I first noticed this is was just two zombies and a pawn firing at them, maybe it's not a big enough sample size to worry about, do they always follow the sound or is it an RNG sort of thing? I've noticed with a larger group of zombies they [will for sure chase a pawn down](https://youtu.be/LZQwrKSzao0).

However, in a situation with a ([modded](https://steamcommunity.com/sharedfiles/filedetails/?id=2290689449&searchtext=embrasure)) embrasure wall, it seems the [zombies ignore the sound](https://youtu.be/23L2SsqYn_8). Likely due to there being no path to the shooter. I know zombies don't currently attack walls but this feels like a situation they maybe should, or at least go for the door next to the pawn

**Comment by Zombiefied7** [comment]
I see. Embrasures are op dont use them with this mod lol. If there is a sound zombies act like manhunting animals, That means they wander in front of the door. Then if they see a pawn use a door, they will attack that door. With embrasures youre always behind walls so the zombies wander in front of the door and thats it

**Comment by Zombiefied7** [comment]
If youd like to make some changes tho to fix this interaction with embrasures go ahead. Relevant file is "JobDriver_ZombieHunt.cs" line 46. Here the zombie gets instructed to attack doors when they lose pathing to a pawn they were hunting. Maybe trigger the same logic when they get shot by a pawn they cant path to

**Comment by Caaz** [comment]
So I got some edits in the [linked PR](https://github.com/Caaz/ZombiefiedZombieApocalpyse/blob/extra_zombie_pathing/Source/JobDriver_ZombieHunt.cs#L29). Seems like it keeps making a toil, but It seems like it never gets to the wall and attacks it. Not sure what I'm missing here exactly but I'm sure it's something in jobs that I'm not fully understanding. Maybe it's not properly targeting the wall? Hm...

Edit: Scratch that got it working, now looking to add settings for configuration
